
-- DROP TABLE PAIS;
CREATE TABLE PAIS (
						IDPAIS			INTEGER PRIMARY KEY,
						NOME			VARCHAR(50) NOT NULL DEFAULT '',
						DTALTERACAO		TIMESTAMP NOT NULL DEFAULT NOW()
				  );
COMMIT;

---------------------------------------------------------------------------------------------------------------------------

-- DROP TABLE ESTADO;
CREATE TABLE ESTADO (
						IDESTADO		INTEGER PRIMARY KEY,
						NOME			VARCHAR(50) NOT NULL,
						IDPAIS			INTEGER NOT NULL DEFAULT 0,
						DTALTERACAO		TIMESTAMP NOT NULL DEFAULT NOW(),
						CONSTRAINT ESTADO_IDPAIS FOREIGN KEY (IDPAIS) REFERENCES PAIS (IDPAIS)
					);
COMMIT;

---------------------------------------------------------------------------------------------------------------------------

-- DROP TABLE CIDADE;
CREATE TABLE CIDADE (
						IDCIDADE		INTEGER PRIMARY KEY,
						NOME			VARCHAR(50) NOT NULL,
						IDESTADO		INTEGER NOT NULL DEFAULT 0,
						DTALTERACAO		TIMESTAMP NOT NULL DEFAULT NOW(),
						CONSTRAINT CIDADE_IDESTADO FOREIGN KEY (IDESTADO) REFERENCES ESTADO (IDESTADO)
					);
COMMIT;

---------------------------------------------------------------------------------------------------------------------------

-- DROP TABLE ENDERECO;
CREATE TABLE ENDERECO (
						IDENDERECO		INTEGER PRIMARY KEY,
						NOME			VARCHAR(50) NOT NULL,
						IDCIDADE		INTEGER NOT NULL DEFAULT 0,
						DTALTERACAO		TIMESTAMP NOT NULL DEFAULT NOW(),
						CONSTRAINT ENDERECO_IDCIDADE FOREIGN KEY (IDCIDADE) REFERENCES CIDADE (IDCIDADE)
					  );
COMMIT;

---------------------------------------------------------------------------------------------------------------------------

--DROP TABLE GRUPO
CREATE TABLE GRUPO(
					IDGRUPO 		INTEGER PRIMARY KEY,
					TIPOUSUARIO 	VARCHAR(1) DEFAULT NULL,
					DESCRICAOGRUPO 	VARCHAR(40) DEFAULT NULL
				  );
COMMIT;

INSERT INTO GRUPO (IDGRUPO,TIPOUSUARIO, DESCRICAOGRUPO) VALUES (1,'A', 'ADMINISTRADORES');
INSERT INTO GRUPO (IDGRUPO,TIPOUSUARIO, DESCRICAOGRUPO) VALUES (2,'O', 'OPERADORES');
COMMIT;

---------------------------------------------------------------------------------------------------------------------------
				  
--DROP TABLE USUARIO
CREATE TABLE USUARIO(
						IDUSUARIO 		INTEGER PRIMARY KEY,
						IDGRUPO 		INTEGER NOT NULL,
						LOGIN 			VARCHAR(10) NOT NULL DEFAULT NULL,
						SENHAUSUARIO 	VARCHAR(20) NOT NULL DEFAULT NULL,
						NOMEUSUARIO 	VARCHAR(40) NOT NULL DEFAULT NULL,
						DTALTERACAO 	TIMESTAMP WITH TIME ZONE,
						FLAGINATIVO 	VARCHAR(1) NOT NULL DEFAULT NULL,
						CONSTRAINT USUARIO_IDGRUPO FOREIGN KEY (IDGRUPO) REFERENCES GRUPO (IDGRUPO)
					);
COMMIT;

INSERT INTO USUARIO (IDUSUARIO, IDGRUPO,LOGIN, SENHAUSUARIO, NOMEUSUARIO,DTALTERACAO,FLAGINATIVO) VALUES (1, 1,'ADMIN', '123', 'ADMINISTRADOR DO SISTEMA', NOW(),'F');
INSERT INTO USUARIO (IDUSUARIO, IDGRUPO,LOGIN, SENHAUSUARIO, NOMEUSUARIO,DTALTERACAO,FLAGINATIVO) VALUES (2, 2,'OPERADOR', '1', 'OPERADOR DO SISTEMA', NOW(),'F');
COMMIT;

---------------------------------------------------------------------------------------------------------------------------

-- DROP TABLE PRODUTO;
CREATE TABLE PRODUTO (
							IDPRODUTO			INTEGER PRIMARY KEY,
							DESCRICAO			VARCHAR(50) NOT NULL,
							TIPOPRODUTO			CHAR(1) NOT NULL DEFAULT '',
							PRECONORMAL			DECIMAL NOT NULL DEFAULT 0,
							PRECOPROMO			DECIMAL NOT NULL DEFAULT 0,
							IDUSUARIOALTERACAO	INTEGER NOT NULL DEFAULT 0,
							FLAGPROMOCAO		CHAR(1) NOT NULL DEFAULT 'F',
							FLAGINATIVO			CHAR(1) NOT NULL DEFAULT 'F',
							DTCADASTRO			TIMESTAMP NOT NULL DEFAULT NOW(),
							DTALTERACAO			TIMESTAMP NOT NULL DEFAULT NOW()
					  );

INSERT INTO PRODUTO( IDPRODUTO, DESCRICAO, PRECONORMAL, PRECOPROMO ) VALUES
(1, 'Cachorro Quente', 3, 2.5);

---------------------------------------------------------------------------------------------------------------------------

-- DROP TABLE ESTOQUE;
CREATE TABLE ESTOQUE (
							IDESTOQUE           INTEGER PRIMARY KEY,
							IDPRODUTO			INTEGER NOT NULL,
							TIPOOPERACAO		CHAR(1) NOT NULL DEFAULT '',
							QUANTIDADE			DECIMAL NOT NULL DEFAULT 0,
							VALORCOMPRA			DECIMAL NOT NULL DEFAULT 0,
							PERCUSTOGERENCIAL	DECIMAL NOT NULL DEFAULT 0,
							PERMARGEMLUCRO		DECIMAL NOT NULL DEFAULT 0,
							VALVENDASUGERIDO	DECIMAL NOT NULL DEFAULT 0,
							VALORUN				DECIMAL NOT NULL DEFAULT 0,
							VALORTOT			DECIMAL NOT NULL DEFAULT 0,
							DTMOVIMENTO			TIMESTAMP NOT NULL DEFAULT NOW(),
							DTALTERACAO			TIMESTAMP NOT NULL DEFAULT NOW(),
							DTATUALIZACAO		TIMESTAMP DEFAULT NOW(),
                            CONSTRAINT ESTOQUE_IDPRODUTO FOREIGN KEY (IDPRODUTO) REFERENCES PRODUTO (IDPRODUTO)
						 );
COMMIT;

INSERT INTO ESTOQUE (IDESTOQUE, IDPRODUTO, TIPOOPERACAO, QUANTIDADE, VALORUN, VALORTOT) VALUES
(1, 1, 'V', 2, 3, 3);

---------------------------------------------------------------------------------------------------------------------------

-- DROP TABLE ESTOQUE;
CREATE TABLE ESTOQUE_SALDO (
								IDESTOQUE	    	INTEGER PRIMARY KEY,
								IDPRODUTO			INTEGER NOT NULL,
								QTDSALDO			DECIMAL NOT NULL DEFAULT 0,
								VALORESTOQUE		DECIMAL NOT NULL DEFAULT 0,
								DTMOVIMENTO			TIMESTAMP NOT NULL DEFAULT NOW(),
								IDUSUARIOALTERACAO	INTEGER NOT NULL DEFAULT 0,
								DTALTERACAO			TIMESTAMP NOT NULL DEFAULT NOW(),
								FN_LOG				VARCHAR(250) DEFAULT '',
	                            CONSTRAINT ESTOQUE_IDPRODUTO FOREIGN KEY (IDPRODUTO) REFERENCES PRODUTO (IDPRODUTO)
					  		);
COMMIT;

---------------------------------------------------------------------------------------------------------------------------

-- DROP TABLE VENDA;
CREATE TABLE VENDA (
							IDVENDA				INTEGER PRIMARY KEY,
							FLAGCANCELADA		CHAR(1) NOT NULL DEFAULT 'F',
							IDCLIENTE			INTEGER NOT NULL DEFAULT 0,
							IDPRODUTO			INTEGER NOT NULL,
							VALORVENDALIQ		DECIMAL NOT NULL,
							TIPOOPERACAO		CHAR(1) NOT NULL DEFAULT '',
							IDENDERECOENTREGA	INTEGER NOT NULL DEFAULT 0,
							OBSERVACAO			VARCHAR(200) NOT NULL DEFAULT '',
							DTMOVIMENTO			TIMESTAMP NOT NULL DEFAULT NOW(),
                            CONSTRAINT ESTOQUE_IDPRODUTO FOREIGN KEY (IDPRODUTO) REFERENCES PRODUTO (IDPRODUTO)
					  );
COMMIT;

---------------------------------------------------------------------------------------------------------------------------

-- DROP TABLE ESTOQUE_AN;
CREATE TABLE ESTOQUE_AN (
							IDVENDA				INTEGER PRIMARY KEY,
							IDESTOQUE			INTEGER NOT NULL,
							IDPRODUTO			INTEGER NOT NULL,
							IDSEQUENCIAVENDA	INTEGER NOT NULL,
							TIPOOPERACAO		CHAR(1) NOT NULL DEFAULT '',
							QUANTIDADE			DECIMAL NOT NULL DEFAULT 0,
							VALORUN				DECIMAL NOT NULL DEFAULT 0,
							VALORTOT			DECIMAL NOT NULL DEFAULT 0,
							DTMOVIMENTO			TIMESTAMP NOT NULL DEFAULT NOW(),
							DTATUALIZACAO		TIMESTAMP DEFAULT NOW(),
                            CONSTRAINT ESTOQUE_AN_IDESTOQUE FOREIGN KEY (IDESTOQUE) REFERENCES ESTOQUE (IDESTOQUE)
						 );
COMMIT;

-------------------------------------------------------------------------------------------------------------------
